In [48]:
from google.cloud import bigquery
from google.oauth2 import service_account 
import pandas as pd
import json

In [72]:
df=pd.read_json("../Dataset_Original/Google_Maps/reviews-estados/review-Alabama/1.json", lines=True)
df

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.140438e+20,Kanisha Mixon,1597168272670,5,Very Personable staff! Beautiful and clean env...,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
1,1.160090e+20,Brandie Hodges,1609899039594,5,Best clothing intown,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
2,1.062399e+20,Sharon King,1547235290843,4,None,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
3,1.049701e+20,Veronica Pierce,1517709403534,5,None,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
4,1.105875e+20,Whitney Waldon Collier,1535245718492,5,None,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
...,...,...,...,...,...,...,...,...
149995,1.165082e+20,Lee Lee,1601666489107,5,Just a good old hardware friendly people,None,None,0x889a89fd92d55353:0x78e335f5e98e75b2
149996,1.080208e+20,Hayward Salter,1621994613217,5,Good people,None,None,0x889a89fd92d55353:0x78e335f5e98e75b2
149997,1.054646e+20,James McBride,1601863228986,4,Good for locals needing supplies to fix damage...,None,None,0x889a89fd92d55353:0x78e335f5e98e75b2
149998,1.118869e+20,Karen Sullivan,1593013285677,1,Very rude female employees at the cash counter...,None,None,0x889a89fd92d55353:0x78e335f5e98e75b2
149999,1.109920e+20,Scott Reid,1573317350293,4,Good hardware and lumber store. Prices on lumb...,None,None,0x889a89fd92d55353:0x78e335f5e98e75b2

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  100 non-null    float64
 1   name     100 non-null    object
 2   time     100 non-null    int64
 3   rating   100 non-null    int64
 4   text     53 non-null     object
 5   pics     1 non-null      object
 6   resp     100 non-null    object
 7   gmap_id  100 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.4+ KB

In [59]:
# Asumiendo que 'df' es tu DataFrame y 'columna_dict' es la columna de tipo dict
df['resp'] = df['resp'].apply(json.dumps)

In [70]:
# Asumiendo que 'df' es tu DataFrame y 'columna_dict' es la columna de tipo dict
df['pics'] = df['pics'].apply(json.dumps)

In [69]:
# Nombre de la columna que quieres verificar
columna_a_verificar = 'pics'

# Recorrer la columna y verificar si hay datos de tipo lista
for index, valor in enumerate(df[columna_a_verificar]):
    if isinstance(valor, list):
        print(f"Encontrado dato de tipo lista en la fila {index}, valor: {valor}")

# Resultado:
# Encontrado dato de tipo lista en la fila 2, valor: [3, 4]

Encontrado dato de tipo lista en la fila 38, valor: [{'url': ['https://lh5.googleusercontent.com/p/AF1QipOIdcXYMYbklLcYakn-bQzweBwEvSMTYPVlkAi7=w150-h150-k-no-p']}]

In [44]:
df

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.140438e+20,Kanisha Mixon,1597168272670,5,Very Personable staff! Beautiful and clean env...,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
1,1.160090e+20,Brandie Hodges,1609899039594,5,Best clothing intown,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
2,1.062399e+20,Sharon King,1547235290843,4,None,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
3,1.049701e+20,Veronica Pierce,1517709403534,5,None,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
4,1.105875e+20,Whitney Waldon Collier,1535245718492,5,None,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
...,...,...,...,...,...,...,...,...
95,1.034367e+20,Dericc Williams,1624420177440,1,Bad attitudes rude and the owner must not care...,None,None,0x88892bb449d44cb3:0x7beaf0b2e3171a49
96,1.034367e+20,Dericc Williams,1624420177440,1,Bad attitudes rude and the owner must not care...,None,None,0x88892bb449d44cb3:0x7beaf0b2e3171a49
97,1.048774e+20,Susie Smith,1602297776261,5,This location does an awesome job! The delive...,None,None,0x88892bb449d44cb3:0x7beaf0b2e3171a49
98,1.168791e+20,Brenda Brown,1598537775889,4,Best pizza I've had in a long time,None,None,0x88892bb449d44cb3:0x7beaf0b2e3171a49
99,1.111581e+20,sonido pachuko king,1611369121997,1,"Terrible service, they don't know how to place...",None,None,0x88892bb449d44cb3:0x7beaf0b2e3171a49

In [74]:
# Proporciona la ruta al archivo de clave de tu cuenta de servicio
credentials = service_account.Credentials.from_service_account_file(
    '../credenciales.json')

# Crea un cliente de BigQuery con tus credenciales
client = bigquery.Client(credentials=credentials, project=credentials.project_id)

# Reemplaza con tu ID de conjunto de datos y tabla
table_id = 'proyecto-final-henry-412703.Datawarehouse_PF.reviews-alabama'

# Carga el DataFrame en BigQuery
job = client.load_table_from_dataframe(df, table_id)

# Espera a que la carga se complete
job.result()

print("Carga completada.")

c:\Users\nico\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:535: UserWarning: Pyarrow could not determine the type of columns: pics, resp.
  warnings.warn(

Carga completada.